---
- name: Common config for all nodes
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Ensure python3 exists on targets (raw bootstrap)
    ansible.builtin.raw: |
      test -x /usr/bin/python3 || (command -v dnf >/dev/null && sudo dnf -y install python3 || sudo yum -y install python3)
    changed_when: false
  vars:
    hosts_lines:
    - "10.0.0.2   master.cdp"
    - "10.0.0.3   node1.cdp"
    - "10.0.0.4   node2.cdp"
    - "10.0.0.5   node3.cdp"
  tasks:
  - name: Disable SELinux (runtime)
    command: setenforce 0
    failed_when: false
    changed_when: false

  - name: Ensure SELinux disabled persistently
    ansible.builtin.replace:
      path: /etc/selinux/config
      regexp: '^SELINUX=.*'
      replace: 'SELINUX=disabled'

  - name: Stop and disable firewalld
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Ensure packages present
    ansible.builtin.yum:
      name:
      - curl
      - unzip
      - tar
      - wget
      - sed
      - gcc
      - openssl-devel
      - openssl
      - krb5-workstation
      - krb5-libs
      - python3
      - java-1.8.0-openjdk-devel
      - snappy
      - openssh-server
      - openssh-clients
      state: present
      update_cache: yes

  - name: Set Java 8 as default
    ansible.builtin.shell: |
      alternatives --set java /usr/lib/jvm/java-1.8.0-openjdk/bin/java || true
      alternatives --set javac /usr/lib/jvm/java-1.8.0-openjdk/bin/javac || true
    changed_when: false

  - name: Ensure chronyd enabled and running
    ansible.builtin.service:
      name: chronyd
      state: started
      enabled: true

  - name: Check if swap file exists
    stat:
      path: /swapfile
    register: swap_file_check

  - name: Create swap file (4GB)
    command: dd if=/dev/zero of=/swapfile bs=1G count=4
    when: not swap_file_check.stat.exists

  - name: Set permissions on swap file
    file:
      path: /swapfile
      mode: '0600'

  - name: Make swap file
    command: mkswap /swapfile
    when: not swap_file_check.stat.exists

  - name: Enable swap
    command: swapon /swapfile
    when: not swap_file_check.stat.exists

  - name: Persist swap in fstab
    lineinfile:
      path: /etc/fstab
      line: '/swapfile none swap sw 0 0'
      state: present

  - name: Ensure /etc/hosts has cluster FQDNs
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        {% for line in hosts_lines %}
        {{ line }}
        {% endfor %}
      marker: "# {mark} CDP_CLUSTER_HOSTS"

- name: Ambari repos and agent on all nodes
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Import Jenkins GPG key (used by repo)
    ansible.builtin.get_url:
      url: https://clemlabs.s3.eu-west-3.amazonaws.com/RPM-GPG-KEY-SHA256-Jenkins
      dest: /tmp/RPM-GPG-KEY-SHA256-Jenkins
    register: download_jenkins_key
    until: download_jenkins_key is success
    retries: 5
    delay: 10
  - name: rpm --import jenkins gpg key
    ansible.builtin.command: rpm --import /tmp/RPM-GPG-KEY-SHA256-Jenkins
    changed_when: false

  - name: Install ODP repo
    ansible.builtin.get_url:
      url: https://clemlabs.s3.eu-west-3.amazonaws.com/centos9-aarch64/odp-release/1.2.2.0-128/odp.repo
      dest: /etc/yum.repos.d/odp.repo
    register: download_odp_repo
    until: download_odp_repo is success
    retries: 5
    delay: 10

  - name: Install Ambari repo
    ansible.builtin.get_url:
      url: https://clemlabs.s3.eu-west-3.amazonaws.com/centos9-aarch64/ambari-release/2.7.9.0.0-61/ambari.repo
      dest: /etc/yum.repos.d/ambari.repo
    register: download_ambari_repo
    until: download_ambari_repo is success
    retries: 5
    delay: 10

  - name: Install ambari-agent (all nodes)
    ansible.builtin.yum:
      name: ambari-agent.aarch64
      state: present

- name: Configure master node
  hosts: master
  become: true
  gather_facts: false
  tasks:
  - name: Install server deps
    ansible.builtin.yum:
      name:
      - odp-select.aarch64
      - ambari-server.aarch64
      - postgresql-server
      - postgresql-contrib
      - postgresql-jdbc
      state: present

  - name: Initialize PostgreSQL if needed
    ansible.builtin.shell: |
      if [ ! -d /var/lib/pgsql/data/base ]; then
        postgresql-setup --initdb || true
      fi
    args:
      executable: /bin/bash

  - name: Configure PostgreSQL (listen_addresses)
    ansible.builtin.lineinfile:
      path: /var/lib/pgsql/data/postgresql.conf
      regexp: "^#?listen_addresses"
      line: "listen_addresses = '*'"
      state: present

  - name: Configure PostgreSQL (pg_hba.conf)
    ansible.builtin.copy:
      dest: /var/lib/pgsql/data/pg_hba.conf
      content: |
        # TYPE  DATABASE        USER            ADDRESS                 METHOD
        local   all             postgres                                peer
        local   all             all                                     md5
        host    all             all             127.0.0.1/32            md5
        host    all             all             ::1/128                 md5
        host    all             all             10.0.0.0/16             md5
        host    all             all             10.0.1.0/24             md5
        host    ambari          ambari          0.0.0.0/0               md5
        host    hive            hive            0.0.0.0/0               md5
        host    ranger          rangeradmin     0.0.0.0/0               md5
      owner: postgres
      group: postgres
      mode: '0600'

  - name: Restart PostgreSQL to apply changes
    ansible.builtin.service:
      name: postgresql
      state: restarted
      enabled: true

  - name: Create PostgreSQL Users
    ansible.builtin.shell: |
      sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='ambari') THEN CREATE ROLE ambari LOGIN PASSWORD 'Ambari123'; END IF; END \$\$;"
      sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='hive') THEN CREATE ROLE hive LOGIN PASSWORD 'HiveUserMeta2025'; ELSE ALTER ROLE hive WITH PASSWORD 'HiveUserMeta2025'; END IF; END \$\$;"
      sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='rangeradmin') THEN CREATE ROLE rangeradmin LOGIN PASSWORD 'Ambari1234'; ELSE ALTER ROLE rangeradmin WITH PASSWORD 'Ambari1234'; END IF; END \$\$;"
      sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'Ambari1234';"
    args:
      executable: /bin/bash

  - name: Create PostgreSQL Databases
    ansible.builtin.shell: |
      sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'ambari'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE ambari OWNER ambari;"
      sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'hive'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE hive OWNER hive;"
      sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'ranger'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE ranger OWNER rangeradmin;"
      sudo -u postgres psql -d ambari -c "CREATE SCHEMA IF NOT EXISTS ambari AUTHORIZATION ambari;"
    args:
      executable: /bin/bash

  - name: Populate Ambari Database Schema
    ansible.builtin.shell: |
      export PGPASSWORD='Ambari123'
      psql -h localhost -p 5432 -U ambari -d ambari -f /var/lib/ambari-server/resources/Ambari-DDL-Postgres-CREATE.sql
    args:
      executable: /bin/bash
    register: db_schema_import
    failed_when: db_schema_import.rc != 0 and "already exists" not in db_schema_import.stderr

  - name: Ambari server setup (PostgreSQL)
    ansible.builtin.command:
      argv:
      - "ambari-server"
      - "setup"
      - "-s"
      - "--database=postgres"
      - "--databasehost=localhost"
      - "--databaseport=5432"
      - "--databasename=ambari"
      - "--databaseusername=ambari"
      - "--databasepassword=Ambari123"
      - "--jdbc-db=postgres"
      - "--jdbc-driver=/usr/share/java/postgresql-jdbc.jar"
      - "-j"
      - "/usr/lib/jvm/java-1.8.0-openjdk"
    register: ambari_setup
    changed_when: ambari_setup.rc == 0
    failed_when: ambari_setup.rc not in [0]

  - name: Hotfix ODP Stack (Fix Bash Syntax Error in hive_service.py)
    ansible.builtin.shell: |
      find /var/lib/ambari-server/resources/stacks -name hive_service.py -exec sed -i 's/| |/|/g' {} +
      find /var/lib/ambari-server/resources/stacks -name hive_service.py -exec sed -i "s/grep -v '\[main\]/grep -v '\[main\]'/g" {} +
    args:
      executable: /bin/bash
    ignore_errors: true

  - name: Ensure Ambari JDBC properties are set (workaround)
    ansible.builtin.lineinfile:
      path: /etc/ambari-server/conf/ambari.properties
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
    - { regexp: '^server.jdbc.url=', line: 'server.jdbc.url=jdbc:postgresql://localhost:5432/ambari' }
    - { regexp: '^server.jdbc.driver=', line: 'server.jdbc.driver=org.postgresql.Driver' }
    - { regexp: '^server.jdbc.database=', line: 'server.jdbc.database=postgres' }
    - { regexp: '^server.jdbc.database_name=', line: 'server.jdbc.database_name=ambari' }
    - { regexp: '^server.jdbc.postgres.schema=', line: 'server.jdbc.postgres.schema=ambari' }
    - { regexp: '^server.jdbc.user.name=', line: 'server.jdbc.user.name=ambari' }
    - { regexp: '^server.jdbc.user.passwd=', line: 'server.jdbc.user.passwd=/etc/ambari-server/conf/password.dat' }
    - { regexp: '^server.jdbc.rca.url=', line: 'server.jdbc.rca.url=jdbc:postgresql://localhost:5432/ambari' }
    - { regexp: '^server.jdbc.rca.driver=', line: 'server.jdbc.rca.driver=org.postgresql.Driver' }
    - { regexp: '^server.jdbc.rca.user.name=', line: 'server.jdbc.rca.user.name=ambari' }
    - { regexp: '^server.jdbc.rca.user.passwd=', line: 'server.jdbc.rca.user.passwd=/etc/ambari-server/conf/password.dat' }
    - { regexp: '^ambari-server.user=', line: 'ambari-server.user=root' }
    - { regexp: '^java.home=', line: 'java.home=/usr/lib/jvm/java-1.8.0-openjdk' }
    - { regexp: '^server.os_family=', line: 'server.os_family=redhat' }
    - { regexp: '^server.os_type=', line: 'server.os_type=redhat9' }

  - name: Ensure Ambari password file exists
    ansible.builtin.copy:
      content: "Ambari123"
      dest: /etc/ambari-server/conf/password.dat
      owner: root
      group: root
      mode: '0600'

  - name: Start ambari-server
    ansible.builtin.service:
      name: ambari-server
      state: started
      enabled: true

  - name: Create console user and set password
    ansible.builtin.user:
      name: console
      groups: wheel
      append: yes
      state: present
  - name: Set console password
    ansible.builtin.shell: echo 'console:1aB@2bC#' | chpasswd

  - name: Append environment variables to root .bashrc
    ansible.builtin.blockinfile:
      path: /root/.bashrc
      marker: "# {mark} ODP_EXPORTS"
      block: |
        export ZOOKEEPER_HOME="/usr/odp/1.2.2.0-128/zookeeper"
        export PATH=$PATH:$ZOOKEEPER_HOME/bin
        export KAFKA_HOME="/usr/odp/1.2.2.0-128/kafka"
        export PATH=$PATH:$KAFKA_HOME/bin
        export NIFI_HOME="/usr/odp/1.2.2.0-128/nifi"
        export PATH=$PATH:$NIFI_HOME/bin
        export SPARK_HOME="/usr/odp/1.2.2.0-128/spark3"
        export PATH=$PATH:$SPARK_HOME/bin
        export HIVE_HOME="/usr/odp/1.2.2.0-128/hive"
        export PATH=$PATH:$HIVE_HOME/bin
        export PATH=$PATH:/usr/local/bin

  - name: Download MySQL connector (yum package missing on OL9)
    ansible.builtin.get_url:
      url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar
      dest: /usr/share/java/mysql-connector-java.jar
      mode: '0644'
    register: download_mysql_connector
    until: download_mysql_connector is success
    retries: 5
    delay: 10

  - name: Ensure MySQL connector in Ambari resources
    ansible.builtin.copy:
      src: /usr/share/java/mysql-connector-java.jar
      dest: /var/lib/ambari-server/resources/mysql-connector-java.jar
      remote_src: yes
      mode: '0644'

  - name: Setup Ambari to use MySQL JDBC driver
    ansible.builtin.command: ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar
    changed_when: false

  - name: Restart Ambari Server to pick up changes
    ansible.builtin.service:
      name: ambari-server
      state: restarted

- name: Configure Ambari Agents (All Nodes)
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Install odp-select and ambari-agent
    ansible.builtin.yum:
      name:
      - odp-select.aarch64
      - ambari-agent.aarch64
      state: present

  - name: Force kill ambari-agent (avoid process lock)
    ansible.builtin.shell: |
      pkill -9 -f ambari_agent || true
      rm -f /var/run/ambari-agent/ambari-agent.pid
      rm -f /run/ambari-agent/ambari-agent.pid
    ignore_errors: true

  - name: Cleanup Ambari Agent certificates (fixes SSL mismatch)
    ansible.builtin.shell: |
      rm -rf /var/lib/ambari-agent/keys/*
      # DO NOT delete data/* as it contains the 'version' file needed by agent
    ignore_errors: true

  - name: Point ambari-agent to master
    ansible.builtin.lineinfile:
      path: /etc/ambari-agent/conf/ambari-agent.ini
      regexp: 'hostname='
      line: 'hostname=master.cdp'
      create: true

  - name: Reload systemd to recognize ambari-agent init script
    ansible.builtin.command: systemctl daemon-reload
    changed_when: false

  - name: Ensure ambari-agent is running and enabled
    ansible.builtin.service:
      name: ambari-agent
      state: restarted
      enabled: true
